#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

gpg_bash_lib_function_extract_trap_cmd() {
   ## Thanks to Richard Hansen - http://stackoverflow.com/a/7287873/2605155
   printf '%s\n' "$3"
}

## Cannot be inside a function, because errtrace might not be set, i.e.
## the function may not have inherited the trap, so the existing trap could not
## be detected from within a function.
## Thanks to Richard Hansen - http://stackoverflow.com/a/7287873/2605155
gpg_bash_lib_internal_existing_trap="$(eval "gpg_bash_lib_function_extract_trap_cmd $(trap -p ERR)")"
