#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## {{{ setup

gpg_bash_lib_function_unit_test_error_handler() {
   echo "$FUNCNAME ERROR!" >&2
   exit 1
}

trap "gpg_bash_lib_function_unit_test_error_handler" ERR

gpg_bash_lib_mydir="$( cd "$( dirname "$0" )" && pwd )"
cd "$gpg_bash_lib_mydir"
cd ../../../

gpg_bash_lib_unit_test_existing_trap="$(trap -p ERR)"

## }}}

## {{{ test 1

source "./usr/lib/gpg-bash-lib/source_all"

gpg_bash_lib_function_init

gpg_bash_lib_function_deinit

if [ ! "$gpg_bash_lib_unit_test_existing_trap" = "$(trap -p ERR)" ]; then
   echo "ERROR!" >&2
   exit 1
fi

## errtrace, pipefail was not set before, it should not be set now.

if test -o errtrace ; then
   echo "ERROR!" >&2
   exit 1
fi

if test -o pipefail ; then
   echo "ERROR!" >&2
   exit 1
fi

## }}}

## {{{ test 2

set -o pipefail
set -o errtrace

source "./usr/lib/gpg-bash-lib/source_all"

gpg_bash_lib_function_init

gpg_bash_lib_function_deinit

if [ ! "$gpg_bash_lib_unit_test_existing_trap" = "$(trap -p ERR)" ]; then
   echo "ERROR!" >&2
   exit 1
fi

## errtrace, pipefail was set before, it should be set now.

if ! test -o errtrace ; then
   echo "ERROR!" >&2
   exit 1
fi

if ! test -o pipefail ; then
   echo "ERROR!" >&2
   exit 1
fi

## }}}
