#!/bin/bash

## Copyright (C) 2012 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e
set -o pipefail
set -o errtrace

gpg_bash_lib_mydir="$( cd "$( dirname "$0" )" && pwd )"
cd "$gpg_bash_lib_mydir"
cd ../../../

if test -o xtrace ; then
   ## TODO: fix
   #bash -x usr/share/gpg-bash-lib/unit-tests/traps_and_shopts
   bash -x usr/share/gpg-bash-lib/unit-tests/verification
else
   usr/share/gpg-bash-lib/unit-tests/traps_and_shopts
   usr/share/gpg-bash-lib/unit-tests/verification
fi
