#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

[ -n "$gpg_bash_lib_script_source_dir" ] || \
   if [ -d "./usr/lib/gpg-bash-lib/modules.d" ]; then
      gpg_bash_lib_script_source_dir="./usr/lib/gpg-bash-lib/modules.d"
   elif [ -d "/usr/lib/gpg-bash-lib/modules.d" ]; then
      gpg_bash_lib_script_source_dir="/usr/lib/gpg-bash-lib/modules.d"
   else
      error "ERROR: $0: variable is unset gpg_bash_lib_script_source_dir unset and could not be auto detected!"
      return 0
   fi

for gpg_bash_lib_source_file in "$gpg_bash_lib_script_source_dir/"*; do
   if [ -x "$gpg_bash_lib_source_file" ]; then
      ## If the last character is a ~, ignore that file,
      ## because it was created by some editor,
      ## which creates backup files.
      if [ "${gpg_bash_lib_source_file: -1}" = "~" ]; then
         true "Skipping $gpg_bash_lib_source_file, because backup file."
         continue
      fi
      ## Skipping files such as .dpkg-old and .dpkg-dist.
      if ( echo "$gpg_bash_lib_source_file" | grep -q ".dpkg-" ); then
         true "Skipping $gpg_bash_lib_source_file, because .dpkg file."
         continue
      fi
      bash -n "$gpg_bash_lib_source_file"
      source "$gpg_bash_lib_source_file"
   else
      true "Skipping $gpg_bash_lib_source_file, because not executable."
   fi
done
